"""New Migration

Revision ID: 1b034339a63c
Revises: 799d21eade95
Create Date: 2024-03-20 16:30:43.417640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b034339a63c'
down_revision: Union[str, None] = '799d21eade95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alcohol_content', sa.Float(), nullable=True),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('packing', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
