"""New Migration

Revision ID: 8681c9039afc
Revises: 1b034339a63c
Create Date: 2024-03-20 16:31:16.172108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8681c9039afc'
down_revision: Union[str, None] = '1b034339a63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alcohol_content', sa.Float(), nullable=True),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('packing', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beer_id'), 'beer', ['id'], unique=False)
    op.drop_index('ix_book_id', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alcohol_content', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flavor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('packing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.create_index('ix_book_id', 'book', ['id'], unique=False)
    op.drop_index(op.f('ix_beer_id'), table_name='beer')
    op.drop_table('beer')
    # ### end Alembic commands ###
